spring.application.name=volunhub-backend

spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/volunhub?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${MYSQL_USERNAME:root}
spring.datasource.password=${MYSQL_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

security.jwt.secret=${JWT_SECRET:volunhub-jwt-secret-key-2026-volunhub-jwt-secret-key}
security.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
